CREATE TABLE dbo.[User] (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    Role INT NOT NULL,
    LoginStatus INT NOT NULL,
    TelegramId BIGINT NULL,
    TelegramChatId BIGINT NULL,
    TelegramUsername NVARCHAR(100) NULL,
    FirstName NVARCHAR(100) NULL,
    LastName NVARCHAR(100) NULL
);

CREATE TABLE dbo.Topic (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    Name NVARCHAR(200) NOT NULL
);

CREATE TABLE dbo.Device (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    MqttClientId NVARCHAR(200) NULL,
    MqttUsername NVARCHAR(200) NULL,
    MqttPassword NVARCHAR(200) NULL,
    IsActive BIT NOT NULL DEFAULT 1,
    DeviceType INT NOT NULL
);

CREATE TABLE dbo.MqttMessage (
    Id UNIQUEIDENTIFIER NOT NULL PRIMARY KEY DEFAULT NEWSEQUENTIALID(),
    Payload NVARCHAR(MAX) NOT NULL,
    CreatedAt DATETIME2 NOT NULL DEFAULT SYSUTCDATETIME(),
    DeviceId UNIQUEIDENTIFIER NOT NULL,
    TopicId UNIQUEIDENTIFIER NOT NULL,
    CONSTRAINT FK_MqttMessage_Device FOREIGN KEY (DeviceId) REFERENCES dbo.Device(Id),
    CONSTRAINT FK_MqttMessage_Topic FOREIGN KEY (TopicId) REFERENCES dbo.Topic(Id)
);

CREATE TABLE dbo.DeviceTopic (
    DeviceId UNIQUEIDENTIFIER NOT NULL,
    TopicId UNIQUEIDENTIFIER NOT NULL,
    EventType INT NOT NULL,
    CONSTRAINT PK_DeviceTopic PRIMARY KEY (DeviceId, TopicId, EventType),
    CONSTRAINT FK_DeviceTopic_Device FOREIGN KEY (DeviceId) REFERENCES dbo.Device(Id),
    CONSTRAINT FK_DeviceTopic_Topic FOREIGN KEY (TopicId) REFERENCES dbo.Topic(Id)
);